name = "synthwave"
background = "#1a0933"
foreground = "#ff7edb"
border = "#b893ff"
accent = "#72f1b8"
title = "#fede5d"

[severity]
critical = "#fe4450"
high     = "#ff8b39"
medium   = "#fede5d"
low      = "#72f1b8"
info     = "#b893ff"
